context("pcrelate2 tests")
library(SeqVarTools)

test_that("pcrelate2", {
    svd <- .testData()
    mypcs <- .testPCs(svd)
    myrel <- pcrelate(svd, pcMat = mypcs, correct=FALSE, verbose=FALSE)
    kin <- pcrelateReadKinship(myrel)
    iterator <- SeqVarBlockIterator(svd, verbose=FALSE)
    myrel2 <- pcrelate2(iterator, pcs = mypcs, verbose=FALSE)
    cols <- c("ID1", "ID2", "kin", "k0", "k2", "nsnp")
    expect_equal(as.data.frame(myrel2$kinBtwn)[,cols], kin[,cols])
    seqClose(svd)
})

test_that("pcrelate2 - variant blocks", {
    svd <- .testData()
    mypcs <- .testPCs(svd)
    myrel <- pcrelate(svd, pcMat = mypcs, correct=FALSE, verbose=FALSE)
    kin <- pcrelateReadKinship(myrel)
    iterator <- SeqVarBlockIterator(svd, variantBlock=500, verbose=FALSE)
    myrel2 <- pcrelate2(iterator, pcs = mypcs, verbose=FALSE)
    cols <- c("ID1", "ID2", "kin", "k0", "k2", "nsnp")
    expect_equal(as.data.frame(myrel2$kinBtwn)[,cols], kin[,cols])
    seqClose(svd)
})

test_that("pcrelate2 - sample blocks", {
    svd <- .testData()
    mypcs <- .testPCs(svd)
    myrel <- pcrelate(svd, pcMat = mypcs, correct=FALSE, verbose=FALSE)
    kin <- pcrelateReadKinship(myrel)
    iterator <- SeqVarBlockIterator(svd, verbose=FALSE)
    myrel2 <- pcrelate2(iterator, pcs = mypcs, sample.block.size=50, verbose=FALSE)
    cols <- c("ID1", "ID2", "kin", "k0", "k2", "nsnp")
    expect_equal(as.data.frame(myrel2$kinBtwn)[,cols], kin[,cols])
    seqClose(svd)
})

test_that("pcrelate2 - sample include", {
    svd <- .testData()
    mypcs <- .testPCs(svd)
    samp.incl <- sample(seqGetData(svd, "sample.id"), 50)
    myrel <- pcrelate(svd, pcMat = mypcs, scan.include=samp.incl, correct=FALSE, verbose=FALSE)
    kin <- pcrelateReadKinship(myrel)
    iterator <- SeqVarBlockIterator(svd, verbose=FALSE)
    myrel2 <- pcrelate2(iterator, pcs = mypcs, sample.include=samp.incl, verbose=FALSE)
    cols <- c("ID1", "ID2", "kin", "k0", "k2", "nsnp")
    expect_equal(as.data.frame(myrel2$kinBtwn)[,cols], kin[,cols])
    seqClose(svd)
})

## this is slow
test_that("pcrelate2 - GenotypeData", {
    gd <- .testHMData()
    mypcs <- .testHMPCs(gd)
    myrel <- pcrelate(gd, pcMat = mypcs, correct=FALSE, verbose=FALSE)
    kin <- pcrelateReadKinship(myrel)
    kin$ID1 <- as.character(kin$ID1)
    kin$ID2 <- as.character(kin$ID2)
    iterator <- GWASTools::GenotypeBlockIterator(gd)
    myrel2 <- pcrelate2(iterator, pcs = mypcs, verbose=FALSE)
    tmp <- dplyr::left_join(kin, as.data.frame(myrel2$kinBtwn), by=c("ID1", "ID2"))
    cols <- c("kin", "k0", "k2", "nsnp")
    expect_equivalent(tmp[,paste0(cols, ".x")], tmp[,paste0(cols, ".y")])
    GWASTools::close(gd)
})
